// fix_final.js — Repair IPAMPage corruption in App.jsx
// Strategy:
//   1. Keep lines 1-3318 (clean - includes CreateVM's return statement)
//   2. Add closing } for CreateVM
//   3. Write a completely clean IPAMPage function
//   4. Keep lines 3930+ (ASSET MANAGEMENT PAGE onwards)

const fs = require('fs');
const path = require('path');
const filePath = path.resolve('C:/caas-dashboard/frontend/src/App.jsx');

const raw = fs.readFileSync(filePath, 'utf8');
const lines = raw.split('\r\n');
const N = lines.length;

console.log('Total lines:', N);
console.log('Line 3318:', JSON.stringify(lines[3317]));
console.log('Line 3319:', JSON.stringify(lines[3318]));
console.log('Line 3930:', JSON.stringify(lines[3929]));

// ---- Verify boundaries ----
if (lines[3317].trim() !== ');') {
  console.error('ERROR: line 3318 is not ");" - got:', lines[3317]);
  process.exit(1);
}
if (!lines[3929].includes('ASSET MANAGEMENT PAGE')) {
  console.error('ERROR: line 3930 is not ASSET MANAGEMENT - got:', lines[3929]);
  process.exit(1);
}

// ---- Build clean IPAMPage function ----
// This is written entirely fresh with no corruption, encoding the full function inline
const cleanIPAMPage = [
'',
'// \u2500\u2500\u2500 IPAM PAGE \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500',
'function IPAMPage({data, loading, error, cachedAt, currentUser, p}) {',
'  const subnets   = data?.subnets || [];',
'  const summary   = data?.summary || {};',
'  const [q, setQ] = useState("");',
'  const [statusF, setStatusF] = useState("all");',
'  const [sortKey, setSortKey] = useState("vlan");',
'  const [sortDir, setSortDir] = useState("asc");',
'  const [refreshing, setRefreshing] = useState(false);',
'  const [loadErr,  setLoadErr]  = useState(null);',
'  const [addModal,   setAddModal]   = useState(false);',
'  const [editEntry,  setEditEntry]  = useState(null);',
'  const [subnetForm, setSubnetForm] = useState({vlan:"",address_cidr:"",name:"",location:"",comments:"",status:"Up"});',
'  const [subnetBusy, setSubnetBusy] = useState(false);',
'  const [subnetMsg,  setSubnetMsg]  = useState(null);',
'',
'  const role       = currentUser?.role || "viewer";',
'  const canRefresh = ["admin","operator"].includes(role);',
'  const canManage  = role === "admin";',
'',
'  const load = async () => {',
'    setLoadErr(null);',
'    try { /* data is loaded by parent via polling */ }',
'    catch(e) { setLoadErr(e.message); }',
'  };',
'',
'  const handleRefresh = async () => {',
'    setRefreshing(true);',
'    try { await refreshIPAMCache(); }',
'    catch(e) { setLoadErr(e.message); }',
'    finally { setRefreshing(false); }',
'  };',
'',
'  // Subnet admin handlers',
'  async function handleAddSubnet(){',
'    if(!subnetForm.address_cidr) return;',
'    setSubnetBusy(true); setSubnetMsg(null);',
'    try{',
'      await addIPAMManualSubnet(subnetForm);',
'      setSubnetMsg({ok:true,text:"Subnet added"});',
'      setAddModal(false); setSubnetForm({vlan:"",address_cidr:"",name:"",location:"",comments:"",status:"Up"});',
'    }catch(e){ setSubnetMsg({ok:false,text:e.message}); }',
'    setSubnetBusy(false);',
'  }',
'  async function handleEditSubnet(){',
'    if(!editEntry) return;',
'    setSubnetBusy(true); setSubnetMsg(null);',
'    try{',
'      await editIPAMManualSubnet(editEntry.subnet_id, subnetForm);',
'      setSubnetMsg({ok:true,text:"Subnet updated"});',
'      setEditEntry(null); setSubnetForm({vlan:"",address_cidr:"",name:"",location:"",comments:"",status:"Up"});',
'    }catch(e){ setSubnetMsg({ok:false,text:e.message}); }',
'    setSubnetBusy(false);',
'  }',
'  async function handleDeleteSubnet(s){',
'    if(!window.confirm("Delete manual subnet "+s.address_cidr+"?")) return;',
'    setSubnetBusy(true); setSubnetMsg(null);',
'    try{',
'      await deleteIPAMManualSubnet(s.subnet_id);',
'      setSubnetMsg({ok:true,text:"Subnet deleted"});',
'    }catch(e){ setSubnetMsg({ok:false,text:e.message}); }',
'    setSubnetBusy(false);',
'  }',
'',
'  // Open VLAN detail tab',
'  const openVlanTab = async (subnet) => {',
'    const tab = window.open("", "_blank");',
'    if (!tab) return;',
'    tab.document.write(`<html><head><title>Loading VLAN ${subnet.vlan}...</title></head><body style="background:#0f0a1e;color:#e2e8f0;font-family:Arial,sans-serif;padding:30px;text-align:center"><p style="margin-top:80px;font-size:18px;">⏳ Loading IP addresses for ${subnet.address_cidr}...</p></body></html>`);',
'    tab.document.close();',
'    try {',
'      const d = await fetchIPAMSubnetIPs(subnet.subnet_id);',
'      const ips = d?.ips || [];',
'      const sm  = d?.summary || {};',
'      const si  = d?.subnet_info || subnet;',
'      const ts  = new Date().toLocaleString();',
'',
'      const statusColor  = (c) => c===1?"#ef4444":c===2?"#10b981":c===4?"#f59e0b":c===8?"#3b82f6":"#64748b";',
'      const statusBg     = (c) => c===1?"#ef444418":c===2?"#10b98118":c===4?"#f59e0b18":c===8?"#3b82f618":"#64748b18";',
'      const statusLabel  = (c) => c===1?"Used":c===2?"Free":c===4?"Reserved":c===8?"Transient":"Unknown";',
'      const pct = sm.percent_used||0;',
'      const barClr = pct>=80?"#ef4444":pct>=50?"#f59e0b":"#10b981";',
'',
'      const rows = ips.map((ip,i) => `',
'        <tr style="background:${i%2===0?"#1a1035":"#130d28"}">',
'          <td style="padding:7px 12px;font-family:monospace;font-weight:600;color:#e2e8f0;font-size:13px">${ip.ip}</td>',
'          <td style="padding:7px 12px">',
'            <span style="padding:2px 9px;border-radius:5px;font-size:11px;font-weight:700;',
'              background:${statusBg(ip.status_code)};color:${statusColor(ip.status_code)};border:1px solid ${statusColor(ip.status_code)}44">',
'              ${statusLabel(ip.status_code)}',
'            </span>',
'          </td>',
'          <td style="padding:7px 12px;color:#94a3b8;font-size:12px">${ip.dns_back_record||(ip.dns_forward_record||"—")}</td>',
'          <td style="padding:7px 12px;color:#64748b;font-size:12px">${ip.description||"—"}</td>',
'          <td style="padding:7px 12px;color:#64748b;font-size:11px">${ip.last_used||"—"}</td>',
'        </tr>`,',
'      ).join("");',
'',
'      tab.document.open();',
'      tab.document.write(`<!DOCTYPE html><html><head>',
'        <title>VLAN ${si.vlan||"—"} · ${si.address_cidr}</title>',
'        <meta charset="UTF-8">',
'        <style>',
'          *{box-sizing:border-box;margin:0;padding:0}',
'          body{background:#0f0a1e;color:#e2e8f0;font-family:Arial,sans-serif;padding:24px}',
'          h2{font-size:20px;font-weight:800;margin-bottom:4px}',
'          .meta{font-size:12px;color:#64748b;margin-bottom:20px}',
'          .kpis{display:flex;gap:12px;flex-wrap:wrap;margin-bottom:20px}',
'          .kpi{background:#1a1035;border:1px solid #2d2060;border-radius:10px;padding:12px 18px;min-width:120px}',
'          .kpi-l{font-size:10px;color:#64748b;font-weight:600;text-transform:uppercase;letter-spacing:.4px}',
'          .kpi-v{font-size:22px;font-weight:800;margin-top:2px}',
'          .bar-wrap{background:#1e1040;border-radius:4px;height:8px;overflow:hidden;margin-top:6px}',
'          .bar-fill{height:100%;border-radius:4px;transition:width .4s}',
'          table{width:100%;border-collapse:collapse;font-size:13px}',
'          th{padding:8px 12px;text-align:left;font-size:11px;color:#64748b;font-weight:600;text-transform:uppercase;letter-spacing:.4px;border-bottom:1px solid #2d2060}',
'          tr:hover td{background:#1e1040!important}',
'          .badge{padding:2px 9px;border-radius:5px;font-size:11px;font-weight:700}',
'        </style>',
'      </head><body>',
'        <h2>📡 VLAN ${si.vlan||"N/A"} · ${si.address_cidr}</h2>',
'        <div class="meta">${si.name||""} ${si.location?("· "+si.location):""} · Generated ${ts}</div>',
'        <div class="kpis">',
'          <div class="kpi"><div class="kpi-l">Total IPs</div><div class="kpi-v" style="color:#60a5fa">${sm.total||0}</div></div>',
'          <div class="kpi"><div class="kpi-l">Used</div><div class="kpi-v" style="color:#ef4444">${sm.used||0}</div></div>',
'          <div class="kpi"><div class="kpi-l">Free</div><div class="kpi-v" style="color:#10b981">${sm.available||0}</div></div>',
'          <div class="kpi"><div class="kpi-l">Reserved</div><div class="kpi-v" style="color:#f59e0b">${sm.reserved||0}</div></div>',
'          <div class="kpi">',
'            <div class="kpi-l">Utilization</div>',
'            <div class="kpi-v" style="color:${barClr}">${pct.toFixed(1)}%</div>',
'            <div class="bar-wrap"><div class="bar-fill" style="width:${Math.min(pct,100)}%;background:${barClr}"></div></div>',
'          </div>',
'        </div>',
'        <table>',
'          <thead><tr>',
'            <th>IP Address</th><th>Status</th><th>DNS / Hostname</th><th>Description</th><th>Last Used</th>',
'          </tr></thead>',
'          <tbody>${rows||\'<tr><td colspan=5 style="padding:24px;text-align:center;color:#64748b">No IP data</td></tr>\'}</tbody>',
'        </table>',
'      </body></html>`);',
'      tab.document.close();',
'    } catch(err) {',
'      tab.document.open();',
'      tab.document.write(`<html><body style="background:#0f0a1e;color:#ef4444;font-family:Arial;padding:30px"><h2>Error</h2><p>${err.message}</p></body></html>`);',
'      tab.document.close();',
'    }',
'  };',
'',
'  const qL = q.toLowerCase();',
'  const filtered = subnets.filter(s => {',
'    const matchQ = !qL || [s.vlan, s.address_cidr, s.name, s.location, s.comments]',
'      .some(x => (x||"").toLowerCase().includes(qL));',
'    const matchS = statusF === "all" || (s.status||"").toLowerCase() === statusF;',
'    return matchQ && matchS;',
'  });',
'',
'  const sorted = [...filtered].sort((a, b) => {',
'    let av = a[sortKey] ?? "", bv = b[sortKey] ?? "";',
'    if (typeof av === "string") av = av.toLowerCase();',
'    if (typeof bv === "string") bv = bv.toLowerCase();',
'    if (av < bv) return sortDir === "asc" ? -1 :  1;',
'    if (av > bv) return sortDir === "asc" ?  1 : -1;',
'    return 0;',
'  });',
'',
'  const toggleSort = (key) => {',
'    if (sortKey === key) setSortDir(d => d === "asc" ? "desc" : "asc");',
'    else { setSortKey(key); setSortDir("asc"); }',
'  };',
'  const sortIcon = (key) => sortKey !== key ? " \u21c5" : sortDir === "asc" ? " \u2191" : " \u2193";',
'  const barColor = (pct) => pct >= 80 ? "#ef4444" : pct >= 50 ? "#f59e0b" : "#10b981";',
'',
'  const thS = (key) => ({',
'    padding:"8px 10px", textAlign:"left", fontWeight:600, fontSize:11,',
'    color:p.textMute, borderBottom:`1px solid ${p.border}`,',
'    cursor:"pointer", whiteSpace:"nowrap", userSelect:"none",',
'    background: sortKey===key ? `${p.accent}22` : "transparent",',
'  });',
'  const tdS = { padding:"7px 10px", fontSize:13, borderBottom:`1px solid ${p.border}`, verticalAlign:"middle" };',
'',
'  return (',
'    <div style={{padding:"0 0 32px"}}>',
'      {/* Header */}',
'      <div style={{display:"flex",alignItems:"center",justifyContent:"space-between",marginBottom:16,flexWrap:"wrap",gap:8}}>',
'        <div>',
'          <div style={{fontWeight:700,fontSize:20,color:p.text}}>📡 IPAM \u2014 IP Address Management</div>',
'          <div style={{fontSize:12,color:p.textMute,marginTop:2}}>SolarWinds IPAM \xb7 {subnets.length} subnets \xb7 last updated {cachedAt}</div>',
'          {(error||data?.error||loadErr) && <div style={{fontSize:12,color:"#f59e0b",marginTop:3}}>\u26a0\ufe0f {error||data?.error||loadErr}</div>}',
'        </div>',
'        <div style={{display:"flex",gap:8,flexWrap:"wrap"}}>',
'          {canManage && (',
'            <button onClick={()=>{ setSubnetForm({vlan:"",address_cidr:"",name:"",location:"",comments:"",status:"Up"}); setSubnetMsg(null); setEditEntry(null); setAddModal(true); }}',
'              style={{padding:"7px 14px",borderRadius:8,border:"none",background:"linear-gradient(135deg,#10b981,#059669)",color:"#fff",fontWeight:600,fontSize:13,cursor:"pointer"}}>',
'              + Add Subnet',
'            </button>',
'          )}',
'          {canRefresh && (',
'            <button onClick={handleRefresh} disabled={refreshing}',
'              style={{padding:"7px 14px",borderRadius:8,border:"none",',
'                background:refreshing?p.border:`linear-gradient(135deg,${p.accent},${p.cyan})`,',
'                color:refreshing?p.textMute:"#fff",fontWeight:600,fontSize:13,cursor:refreshing?"not-allowed":"pointer"}}>',
'              {refreshing ? "\u23f3 Refreshing\u2026" : "\ud83d\udd04 Refresh"}',
'            </button>',
'          )}',
'        </div>',
'      </div>',
'',
'      {/* KPI Cards */}',
'      <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(140px,1fr))",gap:12,marginBottom:20}}>',
'        {[',
'          {label:"Total Subnets", value:summary.total_subnets||0,                   icon:"\ud83d\udce1", color:p.accent},',
'          {label:"Total IPs",     value:(summary.total_ips||0).toLocaleString(),     icon:"\ud83d\udd22", color:p.cyan},',
'          {label:"Used IPs",      value:(summary.used_ips||0).toLocaleString(),      icon:"\ud83d\udd34", color:"#ef4444"},',
'          {label:"Available IPs", value:(summary.available_ips||0).toLocaleString(),icon:"\ud83d\udfe2", color:"#10b981"},',
'          {label:"Reserved",      value:(summary.reserved_ips||0).toLocaleString(), icon:"\ud83d\udd12", color:"#f59e0b"},',
'          {label:"Overall Used",  value:`${summary.percent_used||0}%`,              icon:"\ud83d\udcca", color:barColor(summary.percent_used||0)},',
'        ].map(k=>(',
'          <div key={k.label} style={{background:p.panel,border:`1px solid ${p.border}`,borderRadius:10,padding:"12px 14px",display:"flex",flexDirection:"column",gap:4}}>',
'            <div style={{fontSize:11,color:p.textMute,fontWeight:600,letterSpacing:".4px",textTransform:"uppercase"}}>{k.icon} {k.label}</div>',
'            <div style={{fontSize:22,fontWeight:800,color:k.color}}>{k.value}</div>',
'          </div>',
'        ))}',
'      </div>',
'',
'      {/* Filters */}',
'      <div style={{display:"flex",gap:8,marginBottom:14,flexWrap:"wrap",alignItems:"center"}}>',
'        <input value={q} onChange={e=>setQ(e.target.value)} placeholder="\ud83d\udd0d Search VLAN, subnet, name, location\u2026"',
'          style={{flex:1,minWidth:240,padding:"7px 11px",borderRadius:8,border:`1px solid ${p.border}`,',
'            background:p.panel,color:p.text,fontSize:13,outline:"none"}}/>',
'        <select value={statusF} onChange={e=>setStatusF(e.target.value)}',
'          style={{padding:"7px 11px",borderRadius:8,border:`1px solid ${p.border}`,background:p.panel,color:p.text,fontSize:13}}>',
'          <option value="all">All Status</option>',
'          <option value="up">Up</option>',
'          <option value="down">Down</option>',
'        </select>',
'        <span style={{fontSize:12,color:p.textMute,whiteSpace:"nowrap"}}>{sorted.length} of {subnets.length} subnets</span>',
'      </div>',
'',
'      {/* Table */}',
'      <div style={{background:p.panel,border:`1px solid ${p.border}`,borderRadius:12,overflow:"hidden"}}>',
'        <div style={{overflowX:"auto"}}>',
'          <table style={{width:"100%",borderCollapse:"collapse"}}>',
'            <thead>',
'              <tr style={{background:p.bg}}>',
'                <th style={thS("vlan")}          onClick={()=>toggleSort("vlan")}>VLAN{sortIcon("vlan")}</th>',
'                <th style={thS("address_cidr")}  onClick={()=>toggleSort("address_cidr")}>Subnet / CIDR{sortIcon("address_cidr")}</th>',
'                <th style={thS("name")}           onClick={()=>toggleSort("name")}>Name{sortIcon("name")}</th>',
'                <th style={thS("location")}       onClick={()=>toggleSort("location")}>Location{sortIcon("location")}</th>',
'                <th style={{...thS("total"),   textAlign:"right"}} onClick={()=>toggleSort("total")}>Total{sortIcon("total")}</th>',
'                <th style={{...thS("used"),    textAlign:"right"}} onClick={()=>toggleSort("used")}>Used{sortIcon("used")}</th>',
'                <th style={{...thS("available"),textAlign:"right"}} onClick={()=>toggleSort("available")}>Free{sortIcon("available")}</th>',
'                <th style={{...thS("reserved"),textAlign:"right"}} onClick={()=>toggleSort("reserved")}>Reserved{sortIcon("reserved")}</th>',
'                <th style={{...thS("percent_used"),minWidth:140}}  onClick={()=>toggleSort("percent_used")}>% Used{sortIcon("percent_used")}</th>',
'                <th style={thS("status")}         onClick={()=>toggleSort("status")}>Status{sortIcon("status")}</th>',
'                {canManage&&<th style={{padding:"8px 10px",fontSize:11,color:p.textMute,borderBottom:`1px solid ${p.border}`}}>ACTIONS</th>}',
'              </tr>',
'            </thead>',
'            <tbody>',
'              {sorted.length===0 && (',
'                <tr><td colSpan={canManage?11:10} style={{...tdS,textAlign:"center",color:p.textMute,padding:"32px"}}>No subnets match the filter</td></tr>',
'              )}',
'              {sorted.map((s,i)=>{',
'                const pct = s.percent_used||0;',
'                const bc  = barColor(pct);',
'                return (',
'                  <tr key={s.subnet_id}',
'                    style={{background:i%2===0?"transparent":p.bg+"88",transition:"background .15s"}}',
'                    onMouseEnter={e=>e.currentTarget.style.background=p.accent+"18"}',
'                    onMouseLeave={e=>e.currentTarget.style.background=i%2===0?"transparent":p.bg+"88"}>',
'                    <td style={tdS}>',
'                      <span',
'                        onClick={s.vlan ? ()=>openVlanTab(s) : undefined}',
'                        title={s.vlan ? `Click to view all IPs in ${s.address_cidr}` : undefined}',
'                        style={{padding:"2px 7px",borderRadius:5,background:`${p.cyan}22`,color:p.cyan,fontWeight:700,fontSize:12,fontFamily:"monospace",',
'                          cursor:s.vlan?"pointer":"default",',
'                          textDecoration:s.vlan?"underline":"none",',
'                          textUnderlineOffset:3}}>',
'                        {s.vlan||"\u2014"}',
'                      </span>',
'                    </td>',
'                    <td style={{...tdS,fontFamily:"monospace",fontWeight:600,color:p.text}}>{s.address_cidr||"\u2014"}</td>',
'                    <td style={{...tdS,color:p.textMute,maxWidth:200}}>',
'                      <span title={s.comments||s.description||""} style={{display:"block",overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>',
'                        {s.name||"\u2014"}',
'                      </span>',
'                    </td>',
'                    <td style={{...tdS,color:p.textMute,whiteSpace:"nowrap"}}>{s.location||"\u2014"}</td>',
'                    <td style={{...tdS,textAlign:"right",fontWeight:600}}>{(s.total||0).toLocaleString()}</td>',
'                    <td style={{...tdS,textAlign:"right",color:"#ef4444",fontWeight:600}}>{(s.used||0).toLocaleString()}</td>',
'                    <td style={{...tdS,textAlign:"right",color:"#10b981",fontWeight:700}}>{(s.available||0).toLocaleString()}</td>',
'                    <td style={{...tdS,textAlign:"right",color:"#f59e0b"}}>{(s.reserved||0).toLocaleString()}</td>',
'                    <td style={tdS}>',
'                      <div style={{display:"flex",alignItems:"center",gap:6}}>',
'                        <div style={{flex:1,height:8,borderRadius:4,background:p.border,overflow:"hidden",minWidth:70}}>',
'                          <div style={{width:`${Math.min(pct,100)}%`,height:"100%",borderRadius:4,background:bc,transition:"width .4s"}}/>',
'                        </div>',
'                        <span style={{fontSize:12,fontWeight:700,color:bc,minWidth:38,textAlign:"right"}}>{pct.toFixed(1)}%</span>',
'                      </div>',
'                    </td>',
'                    <td style={tdS}>',
'                      <span style={{padding:"2px 8px",borderRadius:5,fontSize:11,fontWeight:600,',
'                        background:(s.status||"")==="Up"?"#10b98122":"#ef444422",',
'                        color:(s.status||"")==="Up"?"#10b981":"#ef4444"}}>',
'                        {s.status||"Unknown"}',
'                      </span>',
'                    </td>',
'                    {canManage&&<td style={{...tdS,whiteSpace:"nowrap"}}>',
'                      {s.is_manual?(',
'                        <div style={{display:"flex",gap:5}}>',
'                          <button onClick={()=>{ setEditEntry(s); setSubnetForm({vlan:s.vlan||"",address_cidr:s.address_cidr||"",name:s.name||"",location:s.location||"",comments:s.comments||"",status:s.status||"Up"}); setSubnetMsg(null); setAddModal(true); }}',
'                            style={{padding:"2px 8px",borderRadius:5,fontSize:11,fontWeight:600,background:`${p.accent}15`,border:`1px solid ${p.accent}40`,color:p.accent,cursor:"pointer"}}>\u270f\ufe0f Edit</button>',
'                          <button onClick={()=>handleDeleteSubnet(s)}',
'                            style={{padding:"2px 8px",borderRadius:5,fontSize:11,fontWeight:600,background:"#ef444415",border:"1px solid #ef444440",color:"#ef4444",cursor:"pointer"}}>\ud83d\uddd1 Del</button>',
'                        </div>',
'                      ):(',
'                        <span style={{fontSize:10,color:p.textMute}}>SolarWinds</span>',
'                      )}',
'                    </td>}',
'                  </tr>',
'                );',
'              })}',
'            </tbody>',
'          </table>',
'        </div>',
'      </div>',
'',
'      {/* Subnet message */}',
'      {subnetMsg&&<div style={{marginTop:10,padding:"10px 14px",borderRadius:8,fontSize:13,fontWeight:500,',
'        background:subnetMsg.ok?`${p.green||"#10b981"}15`:`${p.red||"#ef4444"}15`,border:`1px solid ${subnetMsg.ok?(p.green||"#10b981"):(p.red||"#ef4444")}40`,',
'        color:subnetMsg.ok?(p.green||"#10b981"):(p.red||"#ef4444")}}>',
'        {subnetMsg.ok?"\u2713":"\u2717"} {subnetMsg.text}',
'      </div>}',
'',
'      {/* Add / Edit Subnet Modal */}',
'      {addModal&&(',
'        <div className="overlay" onClick={()=>{ setAddModal(false); setEditEntry(null); }}>',
'          <div className="modal" style={{width:480}} onClick={e=>e.stopPropagation()}>',
'            <div style={{display:"flex",alignItems:"center",justifyContent:"space-between",marginBottom:16}}>',
'              <div style={{fontWeight:800,fontSize:16}}>{editEntry?"\u270f\ufe0f Edit Subnet":"\u2795 Add Manual Subnet"}</div>',
'              <button className="btn btn-ghost btn-sm" onClick={()=>{ setAddModal(false); setEditEntry(null); }}>\u2715</button>',
'            </div>',
'            <div style={{display:"flex",flexDirection:"column",gap:12}}>',
'              <div className="g2">',
'                <div><label>VLAN ID</label>',
'                  <input value={subnetForm.vlan} onChange={e=>setSubnetForm(f=>({...f,vlan:e.target.value}))} placeholder="e.g. 100"/>',
'                </div>',
'                <div><label>Subnet / CIDR *</label>',
'                  <input value={subnetForm.address_cidr} onChange={e=>setSubnetForm(f=>({...f,address_cidr:e.target.value}))} placeholder="e.g. 10.0.1.0/24"/>',
'                </div>',
'              </div>',
'              <div><label>Name / Description</label>',
'                <input value={subnetForm.name} onChange={e=>setSubnetForm(f=>({...f,name:e.target.value}))} placeholder="e.g. Management Network"/>',
'              </div>',
'              <div className="g2">',
'                <div><label>Location / Site</label>',
'                  <input value={subnetForm.location} onChange={e=>setSubnetForm(f=>({...f,location:e.target.value}))} placeholder="e.g. DC1-Row3"/>',
'                </div>',
'                <div><label>Status</label>',
'                  <select value={subnetForm.status} onChange={e=>setSubnetForm(f=>({...f,status:e.target.value}))}><option>Up</option><option>Down</option></select>',
'                </div>',
'              </div>',
'              <div><label>Comments</label>',
'                <input value={subnetForm.comments} onChange={e=>setSubnetForm(f=>({...f,comments:e.target.value}))} placeholder="Optional notes"/>',
'              </div>',
'              {subnetMsg&&!subnetMsg.ok&&<div style={{fontSize:12,color:(p.red||"#ef4444"),fontWeight:600}}>\u26a0 {subnetMsg.text}</div>}',
'              <div style={{display:"flex",gap:8,justifyContent:"flex-end",marginTop:4}}>',
'                <button className="btn btn-ghost btn-sm" onClick={()=>{ setAddModal(false); setEditEntry(null); }}>Cancel</button>',
'                <button className="btn btn-primary btn-sm" disabled={!subnetForm.address_cidr||subnetBusy}',
'                  onClick={editEntry?handleEditSubnet:handleAddSubnet}>',
'                  {subnetBusy?"\u23f3 Saving\u2026":editEntry?"\ud83d\udcbe Save Changes":"\u2795 Add Subnet"}',
'                </button>',
'              </div>',
'            </div>',
'          </div>',
'        </div>',
'      )}',
'    </div>',
'  );',
'}',
'',
].join('\r\n');

// ---- Assemble new file ----
const before = lines.slice(0, 3318).join('\r\n');   // lines 1-3318 (indexes 0-3317), ends with "  );"
const closeCreateVM = '\r\n}';                        // closes CreateVM
const after = lines.slice(3929).join('\r\n');         // lines 3930+ (index 3929 = ASSET MANAGEMENT)

const newContent = before + closeCreateVM + '\r\n' + cleanIPAMPage + '\r\n' + after;

// ---- Backup and write ----
fs.writeFileSync(filePath + '.bak3', raw, 'utf8');
fs.writeFileSync(filePath, newContent, 'utf8');

// ---- Verify ----
const verification = fs.readFileSync(filePath, 'utf8');
const vLines = verification.split('\r\n');
console.log('New total lines:', vLines.length);

// Count key occurrences
const countOf = (str) => {
  let c = 0;
  for (const l of vLines) if (l.includes(str)) c++;
  return c;
};

console.log('function IPAMPage occurrences:', countOf('function IPAMPage('));
console.log('function CreateVM occurrences:', countOf('function CreateVM('));
console.log('canManage occurrences:', countOf('canManage'));
console.log('ASSET MANAGEMENT PAGE occurrences:', countOf('ASSET MANAGEMENT PAGE'));
console.log('handleAddSubnet occurrences:', countOf('async function handleAddSubnet'));
console.log('handleEditSubnet occurrences:', countOf('async function handleEditSubnet'));
console.log('handleDeleteSubnet occurrences:', countOf('async function handleDeleteSubnet'));

// Find line numbers of key items
for (let i=0; i<vLines.length; i++) {
  if (vLines[i].includes('function IPAMPage(')) console.log('IPAMPage at line:', i+1);
  if (vLines[i].includes('function CreateVM(')) console.log('CreateVM at line:', i+1);
  if (vLines[i].includes('ASSET MANAGEMENT PAGE')) console.log('ASSET MGMT at line:', i+1);
}

console.log('\nDONE - file repaired successfully');
