import sys
sys.stdout.reconfigure(encoding='utf-8')
path = r'c:\caas-dashboard\frontend\src\App.jsx'
lines = open(path, encoding='utf-8').readlines()

new_body = (
    '            {/* \u2500\u2500 Body: donut left + 2\xd72 OEM grid right \u2500\u2500 */}\n'
    '            {extArrays.length>0&&(\n'
    '              <div style={{padding:"14px 16px",display:"flex",gap:16,alignItems:"flex-start",flexWrap:"wrap"}}>\n'
    '\n'
    '                {/* Left: rich donut + 4 kpi stats */}\n'
    '                <div style={{display:"flex",flexDirection:"column",alignItems:"center",gap:8,flexShrink:0,width:120}}>\n'
    '                  {_multiDonut(114,12)}\n'
    '                  <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"3px 8px",width:"100%"}}>\n'
    '                    {[{l:"Used",v:fmtTB(extUsedTB),c:extColor},{l:"Free",v:fmtTB(extFreeTB),c:"#10b981"},{l:"Total",v:fmtTB(extTotalTB),c:"#94a3b8"},{l:"Arrays",v:extArrays.length,c:"#818cf8"}].map(s=>(\n'
    '                      <div key={s.l} style={{textAlign:"center",padding:"3px 0"}}>\n'
    '                        <div style={{fontWeight:900,fontSize:12,color:s.c,fontFamily:"\'Geist Mono\',monospace",lineHeight:1}}>{s.v}</div>\n'
    '                        <div style={{fontSize:8,color:"#475569",fontWeight:700,textTransform:"uppercase",letterSpacing:".3px",marginTop:1}}>{s.l}</div>\n'
    '                      </div>\n'
    '                    ))}\n'
    '                  </div>\n'
    '                </div>\n'
    '\n'
    '                {/* Right: 2x2 OEM grid */}\n'
    '                <div style={{flex:1,minWidth:260,display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}>\n'
    '                  {extTotalTB>0?groupedArrays.map(g=>(\n'
    '                    <div key={g.id} style={{borderRadius:10,overflow:"hidden",border:`1px solid ${g.accentFrom}30`,display:"flex",flexDirection:"column"}}>\n'
    '                      {/* OEM gradient header */}\n'
    '                      <div style={{padding:"6px 9px",background:g.gradient,display:"flex",alignItems:"center",gap:6}}>\n'
    '                        <span style={{fontSize:12}}>{g.icon}</span>\n'
    '                        <span style={{fontSize:10,fontWeight:800,color:"#fff",textTransform:"uppercase",letterSpacing:".8px",flex:1,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{g.label}</span>\n'
    '                        <div style={{padding:"1px 5px",borderRadius:4,background:"#ffffff22",fontSize:9,fontWeight:900,color:"#fff",flexShrink:0}}>{g.pct}%</div>\n'
    '                      </div>\n'
    '                      {/* OEM thin progress bar */}\n'
    '                      <div style={{height:3,background:"#060d1a",overflow:"hidden"}}>\n'
    '                        <div style={{height:"100%",width:`${g.pct}%`,transition:"width 1.2s ease",background:g.gradient,opacity:0.9}}/>\n'
    '                      </div>\n'
    '                      {/* used/total sub-line */}\n'
    '                      <div style={{padding:"3px 9px",background:"#060d1a",display:"flex",justifyContent:"space-between",alignItems:"center",borderBottom:"1px solid #ffffff08"}}>\n'
    '                        <span style={{fontSize:9,color:"#64748b",fontFamily:"\'Geist Mono\',monospace"}}>{fmtTB(g.usedTB)} / {fmtTB(g.totalTB)}</span>\n'
    '                        <span style={{fontSize:9,color:"#334155",fontFamily:"\'Geist Mono\',monospace"}}>{g.arrays.length} array{g.arrays.length!==1?"s":""}</span>\n'
    '                      </div>\n'
    '                      {/* per-array compact rows */}\n'
    '                      <div style={{padding:"5px 9px",background:"#060d1a",display:"flex",flexDirection:"column",gap:4,flex:1}}>\n'
    '                        {g.arrays.map(a=>{\n'
    '                          const c=extCapMap[a.id];\n'
    '                          const vc=_vendorColor(a.vendor);\n'
    '                          if(!c||c.status==="error") return(\n'
    '                            <div key={a.id} style={{display:"flex",alignItems:"center",gap:4}}>\n'
    '                              <div style={{width:2,height:10,borderRadius:1,background:vc,flexShrink:0}}/>\n'
    '                              <span style={{fontSize:10,color:"#64748b",flex:1,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{a.name}</span>\n'
    '                              <span style={{fontSize:9,color:c?"#ef4444":"#f59e0b",fontWeight:700}}>{c?"ERR":"\u2026"}</span>\n'
    '                            </div>\n'
    '                          );\n'
    '                          const pct=c.totalTB>0?Math.min(100,Math.round((c.usedTB/c.totalTB)*100)):0;\n'
    '                          const barClr=pct<70?vc:pct<85?"#f59e0b":"#ef4444";\n'
    '                          return(\n'
    '                            <div key={a.id} style={{marginBottom:1}}>\n'
    '                              <div style={{display:"flex",alignItems:"center",gap:4,marginBottom:2}}>\n'
    '                                <div style={{width:2,height:10,borderRadius:1,background:barClr,flexShrink:0,boxShadow:`0 0 4px ${barClr}99`}}/>\n'
    '                                <span style={{fontSize:10,color:"#e2e8f0",fontWeight:600,flex:1,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{a.name}</span>\n'
    '                                <span style={{fontSize:8,color:vc,fontWeight:700,padding:"0px 4px",borderRadius:3,background:vc+"18",flexShrink:0}}>{_tag(a.vendor)}</span>\n'
    '                                <span style={{fontSize:10,fontWeight:800,color:barClr,fontFamily:"\'Geist Mono\',monospace",minWidth:26,textAlign:"right"}}>{pct}%</span>\n'
    '                              </div>\n'
    '                              <div style={{height:3,borderRadius:2,background:"#1e293b",overflow:"hidden",marginLeft:6}}>\n'
    '                                <div style={{height:"100%",width:`${pct}%`,borderRadius:2,transition:"width 1.1s ease",background:`linear-gradient(90deg,${barClr},${g.accentTo})`,boxShadow:`0 0 5px ${barClr}55`}}/>\n'
    '                              </div>\n'
    '                            </div>\n'
    '                          );\n'
    '                        })}\n'
    '                      </div>\n'
    '                    </div>\n'
    '                  )):(\n'
    '                    <div style={{gridColumn:"1/-1",textAlign:"center",padding:"20px 0",color:"#475569",fontSize:13}}>\n'
    '                      <div style={{fontSize:26,marginBottom:5,opacity:.4}}>\U0001f5c2\ufe0f</div>\n'
    '                      <div style={{fontWeight:600}}>Fetching array capacity\u2026</div>\n'
    '                      <div style={{marginTop:3,color:"#334155",fontSize:11}}>{extArrays.length} array{extArrays.length!==1?"s":""} registered</div>\n'
    '                    </div>\n'
    '                  )}\n'
    '                </div>\n'
    '\n'
    '              </div>\n'
    '            )}\n'
)

# Replace lines 1779..1864 (0-indexed) = lines 1780-1865 (1-indexed)
new_lines = lines[:1779] + [new_body] + lines[1865:]
open(path, 'w', encoding='utf-8').writelines(new_lines)
nl = open(path, encoding='utf-8').readlines()
print('Done. Total lines:', len(nl))
for i in [1778, 1779, 1780]:
    print(f'{i+1}: {nl[i].rstrip()[:90]}')
