P = r"C:\caas-dashboard\migration_backend_new.py"
DT = "date" + "time"
L = []
a = L.append

a('')
a('def _migration_log(plan_id: int, message: str, user: str = "system"):')
a('    from db import get_conn')
a('    import json as _json')
a(f'    from {DT} import {DT}')
a(f'    ts = {DT}.now().strftime("%Y-%m-%d %H:%M:%S")')
a('    with get_conn() as c:')
a('        row = c.execute("SELECT event_log FROM migration_plans WHERE id=?", (plan_id,)).fetchone()')
a('        if not row:')
a('            return')
a('        try:')
a('            log = _json.loads(row["event_log"] or "[]")')
a('        except:')
a('            log = []')
a('        log.append({"ts": ts, "msg": message, "user": user})')
a(f'        c.execute("UPDATE migration_plans SET event_log=?, updated_at={DT}(\'now\') WHERE id=?",')
a('                  (_json.dumps(log), plan_id))')
a('')
a('@app.get("/api/migration/plans")')
a('def list_migration_plans(u=Depends(require_role("admin","operator","viewer"))):')
a('    from db import get_conn')
a('    import json as _json')
a('    with get_conn() as c:')
a('        rows = c.execute("SELECT * FROM migration_plans ORDER BY created_at DESC").fetchall()')
a('    plans = []')
a('    for r in rows:')
a('        d = dict(r)')
a('        for k in ("vm_list","preflight_result","network_mapping","storage_mapping","event_log"):')
a('            if d.get(k):')
a('                try: d[k] = _json.loads(d[k])')
a('                except: pass')
a('        plans.append(d)')
a('    return {"plans": plans}')
a('')
a('@app.get("/api/migration/plans/{plan_id}")')
a('def get_migration_plan(plan_id: int, u=Depends(require_role("admin","operator","viewer"))):')
a('    from db import get_conn')
a('    import json as _json')
a('    with get_conn() as c:')
a('        row = c.execute("SELECT * FROM migration_plans WHERE id=?", (plan_id,)).fetchone()')
a('    if not row:')
a('        from fastapi.responses import JSONResponse')
a('        return JSONResponse(status_code=404, content={"error": "Plan not found"})')
a('    d = dict(row)')
a('    for k in ("vm_list","preflight_result","network_mapping","storage_mapping","event_log"):')
a('        if d.get(k):')
a('            try: d[k] = _json.loads(d[k])')
a('            except: pass')
a('    return {"plan": d}')

with open(P, "a", encoding="utf-8") as f:
    f.write("\n".join(L) + "\n")
print(f"Appended {len(L)} lines")