P = r"C:\caas-dashboard\migration_backend_new.py"
DT = "date" + "time"
L = []
a = L.append

a('')
a('@app.post("/api/migration/plans")')
a('def create_migration_plan(req: dict, u=Depends(require_role("admin","operator"))):')
a('    from db import get_conn')
a('    import json as _json')
a(f'    from {DT} import {DT}')
a('    username = u.get("username", "admin")')
a(f'    ts = {DT}.now().strftime("%Y-%m-%d %H:%M:%S")')
a('    init_log = _json.dumps([{"ts": ts, "msg": f"Migration plan created by {username}", "user": username}])')
a('    with get_conn() as c:')
a('        c.execute("""INSERT INTO migration_plans')
a('            (plan_name, source_platform, source_vcenter, target_platform,')
a('             target_detail, vm_list, preflight_result, network_mapping,')
a('             storage_mapping, migration_tool, status, notes, created_by, event_log)')
a('            VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)""",')
a('            (req.get("plan_name","Untitled"), req.get("source_platform","vmware"),')
a('             _json.dumps(req.get("source_vcenter")), req.get("target_platform",""),')
a('             _json.dumps(req.get("target_detail")), _json.dumps(req.get("vm_list",[])),')
a('             _json.dumps(req.get("preflight_result")), _json.dumps(req.get("network_mapping")),')
a('             _json.dumps(req.get("storage_mapping")), req.get("migration_tool",""),')
a('             "planned", req.get("notes",""), username, init_log))')
a('        plan_id = c.execute("SELECT last_insert_rowid()").fetchone()[0]')
a('    return {"ok": True, "message": "Migration plan created", "plan_id": plan_id}')
a('')
a('@app.delete("/api/migration/plans/{plan_id}")')
a('def delete_migration_plan(plan_id: int, u=Depends(require_role("admin","operator"))):')
a('    from db import get_conn')
a('    with get_conn() as c:')
a('        c.execute("DELETE FROM migration_plans WHERE id=?", (plan_id,))')
a('    return {"ok": True}')
a('')
a('VALID_STATUSES = ("planned","preflight_running","preflight_passed","preflight_failed",')
a('                  "approved","executing","migrating","validating",')
a('                  "completed","failed","cancelled","rolled_back")')
a('')
a('@app.patch("/api/migration/plans/{plan_id}/status")')
a('def update_plan_status(plan_id: int, req: dict, u=Depends(require_role("admin","operator"))):')
a('    from db import get_conn')
a(f'    from {DT} import {DT}')
a('    new_status = req.get("status", "")')
a('    if new_status not in VALID_STATUSES:')
a('        from fastapi.responses import JSONResponse')
a('        return JSONResponse(status_code=400, content={"error": "Invalid status"})')
a('    username = u.get("username", "?")')
a(f'    ts = {DT}.now().strftime("%Y-%m-%d %H:%M:%S")')
a('    with get_conn() as c:')
a('        row = c.execute("SELECT * FROM migration_plans WHERE id=?", (plan_id,)).fetchone()')
a('        if not row:')
a('            from fastapi.responses import JSONResponse')
a('            return JSONResponse(status_code=404, content={"error": "Plan not found"})')
a('        updates = {"status": new_status, "updated_at": ts}')
a('        if new_status == "approved":')
a('            updates["approved_by"] = username')
a('            updates["approved_at"] = ts')
a('        elif new_status == "executing":')
a('            updates["started_at"] = ts')
a('            updates["progress"] = 0')
a('        elif new_status == "completed":')
a('            updates["completed_at"] = ts')
a('            updates["progress"] = 100')
a('        elif new_status == "planned":')
a('            updates["progress"] = 0')
a('            updates["approved_by"] = None')
a('            updates["approved_at"] = None')
a('            updates["started_at"] = None')
a('            updates["completed_at"] = None')
a('        set_clause = ", ".join(f"{k}=?" for k in updates)')
a('        c.execute(f"UPDATE migration_plans SET {set_clause} WHERE id=?",')
a('                  (*updates.values(), plan_id))')
a('    note = req.get("notes", "")')
a("    msg = f\"Status changed to '{new_status}' by {username}\"")
a('    if note:')
a('        msg += f" -- {note}"')
a('    _migration_log(plan_id, msg, username)')
a('    return {"ok": True, "status": new_status}')

with open(P, "a", encoding="utf-8") as f:
    f.write("\n".join(L) + "\n")
print(f"Appended {len(L)} lines")