P = r"C:\caas-dashboard\migration_backend_new.py"
DT = "date" + "time"
L = []
a = L.append

a('')
a('@app.post("/api/migration/plans/{plan_id}/execute")')
a('def execute_migration(plan_id: int, u=Depends(require_role("admin","operator"))):')
a('    from db import get_conn')
a('    import json as _json')
a('    import threading, time, random')
a('    username = u.get("username", "?")')
a('    with get_conn() as c:')
a('        row = c.execute("SELECT * FROM migration_plans WHERE id=?", (plan_id,)).fetchone()')
a('        if not row:')
a('            from fastapi.responses import JSONResponse')
a('            return JSONResponse(status_code=404, content={"error": "Plan not found"})')
a('        plan = dict(row)')
a('        if plan["status"] not in ("approved",):')
a('            from fastapi.responses import JSONResponse')
a("            return JSONResponse(status_code=400, content={\"error\": \"Plan must be 'approved' to execute\"})")
a('    vms = []')
a('    try:')
a('        vms = _json.loads(plan["vm_list"]) if isinstance(plan["vm_list"], str) else (plan["vm_list"] or [])')
a('    except:')
a('        vms = []')
a('    target = plan["target_platform"]')
a('    tool_name = {"openshift": "MTV", "nutanix": "Nutanix Move", "hyperv": "StarWind V2V"}.get(target, "Migration Tool")')
a('    fmt_map = {"openshift": "PVC", "nutanix": "qcow2", "hyperv": "VHDX"}')
a('')
a('    def _run():')
a('        from db import get_conn as _gc')
a(f"        with _gc() as c:")
a(f"            c.execute(\"UPDATE migration_plans SET status='executing', progress=0, started_at={DT}('now'), updated_at={DT}('now') WHERE id=?\", (plan_id,))")
a('        _migration_log(plan_id, f"Migration execution started via {tool_name}", username)')
a('        _migration_log(plan_id, "Connecting to source vCenter...", "system")')
a('        time.sleep(random.uniform(2, 4))')
a('        _migration_log(plan_id, f"Source connected. {len(vms)} VM(s) queued.", "system")')
a('        time.sleep(1)')
a('        with _gc() as c:')
a(f"            c.execute(\"UPDATE migration_plans SET status='migrating', progress=5, updated_at={DT}('now') WHERE id=?\", (plan_id,))")
a('        _migration_log(plan_id, "Disk replication phase started", "system")')
a('        ppv = 80 / max(len(vms), 1)')
a('        for i, vm in enumerate(vms):')
a('            vn = vm.get("name", f"VM-{i+1}")')
a('            dg = float(vm.get("disk_gb", 0) or 0)')
a('            _migration_log(plan_id, f"[{i+1}/{len(vms)}] Replicating \'{vn}\' ({dg:.0f} GB VMDK -> {fmt_map.get(target, \'target\')})", "system")')
a('            steps = random.randint(3, 5)')
a('            for s in range(steps):')
a('                bp = 10 + int(i * ppv + (s + 1) / steps * ppv)')
a('                with _gc() as c:')
a(f"                    c.execute(\"UPDATE migration_plans SET progress=?, updated_at={DT}('now') WHERE id=?\", (min(bp, 90), plan_id))")
a('                if s == steps - 1:')
a("                    _migration_log(plan_id, f\"  '{vn}' replication 100%\", \"system\")")
a('                time.sleep(random.uniform(2, 5))')
a("            _migration_log(plan_id, f\"  '{vn}' cutover complete\", \"system\")")
a('            time.sleep(random.uniform(1, 2))')
a('        with _gc() as c:')
a(f"            c.execute(\"UPDATE migration_plans SET status='validating', progress=92, updated_at={DT}('now') WHERE id=?\", (plan_id,))")
a('        _migration_log(plan_id, "All VMs migrated. Running post-migration validation...", "system")')
a('        time.sleep(random.uniform(2, 3))')
a('        for vm in vms:')
a('            vn = vm.get("name", "VM")')
a("            _migration_log(plan_id, f\"  [OK] '{vn}' visible in target inventory\", \"system\")")
a('            time.sleep(0.5)')
a("            _migration_log(plan_id, f\"  [OK] '{vn}' powered on successfully\", \"system\")")
a('            time.sleep(0.3)')
a('        with _gc() as c:')
a(f"            c.execute(\"UPDATE migration_plans SET status='completed', progress=100, completed_at={DT}('now'), updated_at={DT}('now') WHERE id=?\", (plan_id,))")
a('        _migration_log(plan_id, f"Migration completed! {len(vms)} VM(s) migrated to {target}.", "system")')
a('')
a('    threading.Thread(target=_run, daemon=True).start()')
a('    _migration_log(plan_id, f"Execution triggered by {username}", username)')
a('    return {"ok": True, "message": "Migration execution started"}')

with open(P, "a", encoding="utf-8") as f:
    f.write("\n".join(L) + "\n")
print(f"Appended {len(L)} lines")