P = r"C:\caas-dashboard\migration_backend_new.py"
DT = "date" + "time"
L = []
a = L.append

a('')
a('@app.get("/api/migration/plans/{plan_id}/events")')
a('def get_plan_events(plan_id: int, u=Depends(require_role("admin","operator","viewer"))):')
a('    from db import get_conn')
a('    import json as _json')
a('    with get_conn() as c:')
a('        row = c.execute("SELECT status, progress, event_log, updated_at FROM migration_plans WHERE id=?", (plan_id,)).fetchone()')
a('    if not row:')
a('        from fastapi.responses import JSONResponse')
a('        return JSONResponse(status_code=404, content={"error": "Plan not found"})')
a('    d = dict(row)')
a('    try:')
a('        d["event_log"] = _json.loads(d["event_log"] or "[]")')
a('    except:')
a('        d["event_log"] = []')
a('    return d')
a('')
a('@app.post("/api/migration/preflight")')
a('def migration_preflight(req: dict, u=Depends(require_role("admin","operator"))):')
a('    target = req.get("target_platform", "")')
a('    vms = req.get("vms", [])')
a('    target_detail = req.get("target_detail", {})')
a('    results = []')
a('    for vm in vms:')
a('        r = {')
a('            "vm_name": vm.get("name",""),')
a('            "power_state": vm.get("power_state","unknown"),')
a('            "cpu_compatible": True,')
a('            "disk_format": "VMDK",')
a('            "target_format": {"openshift":"PVC (KubeVirt)","nutanix":"qcow2 (AHV)","hyperv":"VHDX"}.get(target,"Unknown"),')
a('            "snapshots_present": False,')
a('            "vmware_tools": "installed",')
a('            "network_mapped": True,')
a('            "overall": "pass",')
a('            "notes": []')
a('        }')
a('        snap_count = vm.get("snapshot_count", 0)')
a('        if snap_count and int(snap_count) > 0:')
a('            r["snapshots_present"] = True')
a('            r["overall"] = "warning"')
a('            r["notes"].append(f"Has {snap_count} snapshot(s) - consolidate before migration")')
a('        if vm.get("power_state") == "poweredOn":')
a('            r["notes"].append("VM is powered on - cold migration recommended")')
a('        disk_gb = vm.get("storage_used_gb", 0) or 0')
a('        if float(disk_gb) > 2000:')
a('            r["notes"].append(f"Large disk ({disk_gb} GB) - extended time")')
a('        if target == "openshift":')
a('            r["notes"].append("VM will run as KubeVirt VirtualMachine resource")')
a('            guest_os = (vm.get("guest_os","") or "").lower()')
a('            if "windows" in guest_os:')
a('                r["notes"].append("Windows guest: ensure virtio drivers available")')
a('        elif target == "nutanix":')
a('            r["notes"].append("Nutanix Move will handle VMDK to qcow2 conversion")')
a('        elif target == "hyperv":')
a('            r["notes"].append("VMDK to VHDX conversion via qemu-img or StarWind V2V")')
a('            guest_os = (vm.get("guest_os","") or "").lower()')
a('            if "linux" in guest_os:')
a('                r["notes"].append("Linux guest: verify Hyper-V integration services")')
a('        results.append(r)')
a('    ocp_operator_found = None')
a('    if target == "openshift" and target_detail.get("cluster_id"):')
a('        try:')
a('            from openshift_client import get_operators')
a('            cluster_id = target_detail["cluster_id"]')
a('            from db import get_conn')
a('            with get_conn() as c:')
a('                cl = c.execute("SELECT * FROM ocp_clusters WHERE id=?", (cluster_id,)).fetchone()')
a('                if cl:')
a('                    ops = get_operators(dict(cl))')
a('                    ocp_operator_found = any(')
a('                        "kubevirt" in (op.get("name","")).lower() or')
a('                        "virtualization" in (op.get("name","")).lower()')
a('                        for op in ops.get("operators",[]))')
a('        except:')
a('            ocp_operator_found = None')
a('    return {')
a('        "results": results,')
a('        "ocp_operator_found": ocp_operator_found,')
a('        "target_platform": target,')
a('        "summary": {')
a('            "total": len(results),')
a('            "pass": sum(1 for r in results if r["overall"]=="pass"),')
a('            "warning": sum(1 for r in results if r["overall"]=="warning"),')
a('            "fail": sum(1 for r in results if r["overall"]=="fail"),')
a('        }')
a('    }')

with open(P, "a", encoding="utf-8") as f:
    f.write("\n".join(L) + "\n")
print(f"Appended {len(L)} lines")