import base64, sys
# The new migration backend code is stored as base64 in a separate file
# Let me just write it using a Python script file approach
path = r"C:\caas-dashboard\migration_backend_new.py"
f = open(path, "w", encoding="utf-8")
f.write("# \n")
f.write("#  Magic Migrate - Cross-Hypervisor VM Migration Plans (Full Lifecycle)\n")
f.write("#\n\n")
f.write("def _init_migration_db():\n")
f.write("    from db import get_conn\n")
f.write("    with get_conn() as c:\n")
f.write("        c.execute(\"\"\"CREATE TABLE IF NOT EXISTS migration_plans (\n")
f.write("            id              INTEGER PRIMARY KEY AUTOINCREMENT,\n")
f.write("            plan_name       TEXT NOT NULL,\n")
f.write("            source_platform TEXT NOT NULL DEFAULT 'vmware',\n")
f.write("            source_vcenter  TEXT,\n")
f.write("            target_platform TEXT NOT NULL,\n")
f.write("            target_detail   TEXT,\n")
f.write("            vm_list         TEXT,\n")
f.write("            preflight_result TEXT,\n")
f.write("            network_mapping TEXT,\n")
f.write("            storage_mapping TEXT,\n")
f.write("            migration_tool  TEXT,\n")
f.write("            status          TEXT NOT NULL DEFAULT 'planned',\n")
f.write("            progress        INTEGER DEFAULT 0,\n")
f.write("            event_log       TEXT DEFAULT '[]',\n")
f.write("            notes           TEXT DEFAULT '',\n")
f.write("            approved_by     TEXT,\n")
f.write("            approved_at     TEXT,\n")
f.write("            started_at      TEXT,\n")
f.write("            completed_at    TEXT,\n")
f.write("            created_by      TEXT,\n")
f.write("            created_at      TEXT DEFAULT (date" + "time('now')),\n")
f.write("            updated_at      TEXT DEFAULT (date" + "time('now'))\n")
f.write("        )\"\"\")\n")
f.close()
print("Part 1 done:", __import__("os").path.getsize(path), "bytes")